### ISSUE TITLE
Is the output size must (512,768) or  (768, 1216)

### ISSUE THREAD

**Issue by xiaohutongxue-sunny** [ali-vilab/UniAnimate#33]
when i modify output size in UniAnimate_infer_long.yaml  to (768, 1368)  an error occured, 
Traceback (most recent call last):
  File "/home/UniAnimate/inference.py", line 18, in <module>
    INFER_ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)
  File "/home/UniAnimate/utils/registry.py", line 107, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/UniAnimate/utils/registry_class.py", line 7, in build_func
    return build_from_config(cfg, registry, **kwargs)
  File "/home/UniAnimate/utils/registry.py", line 69, in build_from_config
    raise Exception(f"Failed to invoke function {req_type_entry}, with {e}")
Exception: Failed to invoke function <function inference_unianimate_long_entrance at 0x7fb6cf08e0d0>, with Sizes of tensors must match except in dimension 1. Expected size 44 but got size 43 for tensor number 1 in the list.

**Comment by wangxiang1230** [comment]
Hi, thanks for your attention. The input resolution should be divisible by 64 since vae and 3d-unet are used.
