### ISSUE TITLE
KeyError: 'inference_unianimate_entrance not found in INFER_ENGINE registry'

### ISSUE THREAD

**Issue by Inmiy** [ali-vilab/UniAnimate#48]
按照说明流程安装后，执行python inference.py --cfg configs/UniAnimate_infer.yaml 报错了，以下是报错信息：
Traceback (most recent call last):
  File "D:\0xProgramTool\Anaconda3\Miniconda3\envs\UniAnimate-GradioUI\inference.py", line 18, in <module>
    INFER_ENGINE.build(dict(type=cfg_update.TASK_TYPE), cfg_update=cfg_update.cfg_dict)
  File "D:\0xProgramTool\Anaconda3\Miniconda3\envs\UniAnimate-GradioUI\utils\registry.py", line 107, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\0xProgramTool\Anaconda3\Miniconda3\envs\UniAnimate-GradioUI\utils\registry_class.py", line 7, in build_func
    return build_from_config(cfg, registry, **kwargs)
  File "D:\0xProgramTool\Anaconda3\Miniconda3\envs\UniAnimate-GradioUI\utils\registry.py", line 55, in build_from_config
    raise KeyError(f"{req_type} not found in {registry.name} registry")
KeyError: 'inference_unianimate_entrance not found in INFER_ENGINE registry'
不知道是哪里出问题了。

**Comment by wangxiang1230** [comment]
Hi, we have updated the code and fixed this issue for Windows users. Please refer to https://github.com/ali-vilab/UniAnimate/blob/dfa7598b8368d22af9d8e89030220e3ae47d48ee/utils/registry.py#L55-L67 

You can also refer to this issue(https://github.com/ali-vilab/UniAnimate/issues/46) for more details.
